### PR TITLE
Add remove old session info to README

### PR DESCRIPTION
**Pull request by unansweredocd**
This pull request will add info to the FAQ in the readme file that explains what people have to do to remove the old session data. It also adds a section for Arch Linux users on where to find this directory.

### CODE REVIEW

**Comment by EionRobb** [comment]
That's not quite right. 

The arch Linux specific bit isn't just for arch but for bitlbee installations (as opposed to eg pidgin or finch)

Rather than specifying $purpledir, you should suggest the more common ~/.purple

**Comment by unansweredocd** [comment]
I've changed the file according to your comment. Is this what you meant?

**Comment by majn** [comment]
Thanks!

**Comment by unansweredocd** [comment]
No problem. I'll be working on #360 too. Being able to help in this way is pretty cool. Feel free to tag me in stuff you need doing and before I forget, thanks for doing awesome work.

**Pull request merged**
