### PR TITLE
Enable stack smashing protection

### PR DESCRIPTION
**Pull request by carpikes**
Same PR as the one in tgl. It adds compiler flags "-fstack-protector-strong" and "-D_FORTIFY_SOURCE=2", they increase security (protecting from stack smashing) in a production environment and allow developers to find bugs easily.

### CODE REVIEW

**Comment by BenWiederhake** [comment]
``` +ifeq "$(CC)" "gcc" `

**Comment by carpikes** [comment]
The first two solutions that I can think are:
1. `$(CC) -fstack-protector-strong 2>&1 | grep 'stack-protector'strong' | wc -l`.
It returns 1 if is not available, 0 if it's available. But this command needs grep and wc. 
2. Check if the word 'gcc' is in the compiler name. (How?)

**Comment by BenWiederhake** [comment]
Your second option probably won't work reliably on Apple.

Your first option sounds perfect, as we use and expect grep anyway, and wc should be installed on most systems.

Thanks for your work, btw!

**Comment by carpikes** [comment]
Perfect :) Just changed `grep '...' | wc -l` to `grep -c '...'`, it should be the same, but faster.

**Comment by BenWiederhake** [comment]
Looks good.  I'll squash it though, as two of three commits are just fixes of the first commit.

**Comment by BenWiederhake** [comment]
I'm too dump to click 'squash', apparently.  Other than that, let's hope the `2&>1` won't break on FreeBSD.

**Comment by rodneyrod** [comment]
@BenWiederhake Would you like someone to test that? I could download a FreeBSD VM tonight and give it a spin.

**Comment by BenWiederhake** [comment]
That would be nice, yes please.

**Comment by rodneyrod** [comment]
So I got a PC-BSD VM installed and I tried to build telegram-purple, I got ./configure to work after installing pkgconf but when I tried to make I got a 'Need an operator' error on lines 36, 38, 48 and 51, after that make fails.

Anything else you guys need to test feel free to ping me.

**Comment by BenWiederhake** [comment]
"Need an operator"?  That doesn't sound like an error message from either Make, our makefile, the compiler, or anything else I know.
Can you give more details about the error message?

**Comment by rodneyrod** [comment]
I wish I could give you more details but that's all the make process spits out, no logs or anything AFAIK.
I can post the lines from the makefile that are causing issue here if that helps, I'm going to try and install FreeBSD instead, see if this issue persists with that.

**Comment by BenWiederhake** [comment]
> that's all the make process spits out
Well, telling us what it spits out would be a helpful start.

Also, please note that you'll need GNU make, not BSD make, and it's called `gmake` on FreeBSD, so maybe try that on PC-BSD.  Easy way to check:

**Comment by rodneyrod** [comment]
I already told you what the errors were, they are, I'll paste exactly the output on my end. I can't provide any more information than what I'm given.

`make: "/PATH/TO/telegram-purple/Makefile" line 36: Need an operator
make: "/PATH/TO/telegram-purple/Makefile" line 38: Need an operator
make: "/PATH/TO/telegram-purple/Makefile" line 48: Need an operator
make: "/PATH/TO/telegram-purple/Makefile" line 51: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /PATH/TO/telegram-purple/`

make --version doesn't return anything besides the list of flags you can use for make
make -V MAKE_VERSION returns 20151220

**Comment by rodneyrod** [comment]
Looks like I may have been using BSD make, will try again with gmake.

**Comment by rodneyrod** [comment]
Got a better output with gmake, however it doesn't compile and displays the following errors:
`gmake -C tgl libs/libtgl.a
gmake[1]: Entering directory '/usr/home/username/git/telegram-purple/tgl'
gcc -I. -I. -g -O2  -I/usr/local/include -I/usr/include -I/usr/include  -DHAVE_CONFIG_H -Wall -Wextra -Werror -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -iquote ./tl-parser -c -MP -MD -MF dep/tl-parser.d -MQ objs/tl-parser.o -o objs/tl-parser.o tl-parser/tl-parser.c
In file included from tl-parser/tl-parser.c:38:0:
tl-parser/portable_endian.h:56:0: error: "be16toh" redefined [-Werror]
 # define be16toh(x) betoh16(x)
 ^
In file included from tl-parser/portable_endian.h:54:0,
                 from tl-parser/tl-parser.c:38:
/usr/include/sys/endian.h:75:0: note: this is the location of the previous definition
 #define be16toh(x) bswap16((x))
 ^
In file included from tl-parser/tl-parser.c:38:0:
tl-parser/portable_endian.h:57:0: error: "le16toh" redefined [-Werror]
 # define le16toh(x) letoh16(x)
 ^
In file included from tl-parser/portable_endian.h:54:0,
                 from tl-parser/tl-parser.c:38:
/usr/include/sys/endian.h:78:0: note: this is the location of the previous definition
 #define le16toh(x) ((uint16_t)(x))
 ^
In file included from tl-parser/tl-parser.c:38:0:
tl-parser/portable_endian.h:59:0: error: "be32toh" redefined [-Werror]
 # define be32toh(x) betoh32(x)
 ^
In file included from tl-parser/portable_endian.h:54:0,
                 from tl-parser/tl-parser.c:38:
/usr/include/sys/endian.h:76:0: note: this is the location of the previous definition
 #define be32toh(x) bswap32((x))
 ^
In file included from tl-parser/tl-parser.c:38:0:
tl-parser/portable_endian.h:60:0: error: "le32toh" redefined [-Werror]
 # define le32toh(x) letoh32(x)
 ^
In file included from tl-parser/portable_endian.h:54:0,
                 from tl-parser/tl-parser.c:38:
/usr/include/sys/endian.h:79:0: note: this is the location of the previous definition
 #define le32toh(x) ((uint32_t)(x))
 ^
In file included from tl-parser/tl-parser.c:38:0:
tl-parser/portable_endian.h:62:0: error: "be64toh" redefined [-Werror]
 # define be64toh(x) betoh64(x)
 ^
In file included from tl-parser/portable_endian.h:54:0,
                 from tl-parser/tl-parser.c:38:
/usr/include/sys/endian.h:77:0: note: this is the location of the previous definition
 #define be64toh(x) bswap64((x))
 ^
In file included from tl-parser/tl-parser.c:38:0:
tl-parser/portable_endian.h:63:0: error: "le64toh" redefined [-Werror]
 # define le64toh(x) letoh64(x)
 ^
In file included from tl-parser/portable_endian.h:54:0,
                 from tl-parser/tl-parser.c:38:
/usr/include/sys/endian.h:80:0: note: this is the location of the previous definition
 #define le64toh(x) ((uint64_t)(x))
 ^
cc1: all warnings being treated as errors
gmake[1]: *** [Makefile.tl-parser:4: objs/tl-parser.o] Error 1
gmake[1]: Leaving directory '/usr/home/username/git/telegram-purple/tgl'
gmake: *** [Makefile:87: tgl/libs/libtgl.a] Error 2
`

**Comment by rodneyrod** [comment]
gmake worked, forgot about that little BSD quirk, however it now fails with another error

gmake -C tgl libs/libtgl.a
gmake[1]: Entering directory '/usr/home/username/git/telegram-purple/tgl'
gcc -I. -I. -g -O2  -I/usr/local/include -I/usr/include -I/usr/include  -DHAVE_CONFIG_H -Wall -Wextra -Werror -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -iquote ./tl-parser -c -MP -MD -MF dep/tl-parser.d -MQ objs/tl-parser.o -o objs/tl-parser.o tl-parser/tl-parser.c
In file included from tl-parser/tl-parser.c:38:0:
tl-parser/portable_endian.h:56:0: error: "be16toh" redefined [-Werror]
 # define be16toh(x) betoh16(x)
 ^
In file included from tl-parser/portable_endian.h:54:0,
                 from tl-parser/tl-parser.c:38:
/usr/include/sys/endian.h:75:0: note: this is the location of the previous definition
 #define be16toh(x) bswap16((x))
 ^
In file included from tl-parser/tl-parser.c:38:0:
tl-parser/portable_endian.h:57:0: error: "le16toh" redefined [-Werror]
 # define le16toh(x) letoh16(x)
 ^
In file included from tl-parser/portable_endian.h:54:0,
                 from tl-parser/tl-parser.c:38:
/usr/include/sys/endian.h:78:0: note: this is the location of the previous definition
 #define le16toh(x) ((uint16_t)(x))
 ^
In file included from tl-parser/tl-parser.c:38:0:
tl-parser/portable_endian.h:59:0: error: "be32toh" redefined [-Werror]
 # define be32toh(x) betoh32(x)
 ^
In file included from tl-parser/portable_endian.h:54:0,
                 from tl-parser/tl-parser.c:38:
/usr/include/sys/endian.h:76:0: note: this is the location of the previous definition
 #define be32toh(x) bswap32((x))
 ^
In file included from tl-parser/tl-parser.c:38:0:
tl-parser/portable_endian.h:60:0: error: "le32toh" redefined [-Werror]
 # define le32toh(x) letoh32(x)
 ^
In file included from tl-parser/portable_endian.h:54:0,
                 from tl-parser/tl-parser.c:38:
/usr/include/sys/endian.h:79:0: note: this is the location of the previous definition
 #define le32toh(x) ((uint32_t)(x))
 ^
In file included from tl-parser/tl-parser.c:38:0:
tl-parser/portable_endian.h:62:0: error: "be64toh" redefined [-Werror]
 # define be64toh(x) betoh64(x)
 ^
In file included from tl-parser/portable_endian.h:54:0,
                 from tl-parser/tl-parser.c:38:
/usr/include/sys/endian.h:77:0: note: this is the location of the previous definition
 #define be64toh(x) bswap64((x))
 ^
In file included from tl-parser/tl-parser.c:38:0:
tl-parser/portable_endian.h:63:0: error: "le64toh" redefined [-Werror]
 # define le64toh(x) letoh64(x)
 ^
In file included from tl-parser/portable_endian.h:54:0,
                 from tl-parser/tl-parser.c:38:
/usr/include/sys/endian.h:80:0: note: this is the location of the previous definition
 #define le64toh(x) ((uint64_t)(x))
 ^
cc1: all warnings being treated as errors
gmake[1]: *** [Makefile.tl-parser:4: objs/tl-parser.o] Error 1
gmake[1]: Leaving directory '/usr/home/username/git/telegram-purple/tgl'
gmake: *** [Makefile:87: tgl/libs/libtgl.a] Error 2

**Comment by BenWiederhake** [comment]
We really should make a proper guide for FreeBSD, sorry.

**Pull request merged**
