### PR TITLE
updated state for Debian

### PR DESCRIPTION
**Pull request by bwildenhain**
There is currently no package to be proposed to enter Debian.

### CODE REVIEW

**Comment by BenWiederhake** [comment]
You're absolutely right.  I planned to make this part of 1.4.0, as commit 6c3f37392a8b8653694715f27c6152c72bb1d7ef is already available on dev-1.4.0.  Also note that dev-1.4.0 contains `debian-{master,devel}`, so it gets easier for users to build their own packages.

**Comment by kchr** [comment]
Do you need any volunteers for maintaining the Debian package?

**Comment by BenWiederhake** [comment]
The problem lies in the instability of the plugin.  I recently wrote this email to someone to explain all the details.  I should probably work it into the Readme:

> Sorry to disappoint you, but I stopped my efforts to get this into Debian.
>
> Telegram (the company) is moving too fast, and our implementation is so far from feature-complete that users would be too disappointed.
>
> Also, our implementation is quite buggy, and we don't have the resources to fix all of those.
>
> Also, we're building on libtgl, which is an unmaintained, crappy library that was designed as a one-shot thing, for use by the author only. Reimplementing that is a Herculian task, because MTProto (the protocol of Telegram) is incredibly complex and unnecessarily fiddly and stateful.  (E.g., each query of encrypted chats has to include the message number of the previous query of the same chat.)
>
> Also, there are other implementations up and coming, mostly because Telegram (the company) released tdlib, which supposedly handles all the communication with Telegram, and offers a simple API.  I wish those projects good luck. [1]
>
> So thanks for asking, but I don't think anymore that this belongs into the Debian repository.  (I don't have anything against it per se, it's just a very long way until it's ready for that.)
>
> [1] https://github.com/gdouezangrard/bitlbee-telegram

So the way to get it into Debian, which I support btw, is either by fixing all the bugs and unavailable API points of tgl, or switching to tdlib directly.  I can take over the OpenSSL issue and try to make it compatible to libgcrypt/libressl/whatever.

**Comment by BenWiederhake** [comment]
Should be fixed in [v1.4.1](https://github.com/majn/telegram-purple/releases/tag/v1.4.1).

**Pull request closed without merging**
