### PR TITLE
Adding AppData file

### PR DESCRIPTION
**Pull request by Sesivany**
AppData file integrates the Telegram plugin with software centers that use AppStream/AppData format: http://www.freedesktop.org/software/appstream/docs/

### CODE REVIEW

**Comment by BenWiederhake** [comment]
The file you want to add says `<project_license>LGPL-2.1</project_license>` but the project is GPL2+

-- Only subjective criticism below this line! --

I've never heard of AppStream, so I wouldn't say that it's "widely used". What exactly does the user gain from using it? The user still has to `./configure && make && sudo make install`, so I don't see the point.

The project already contains support specific for Fedora and RHEL (the `rpm/` files, as far as I understand, although I'm only really familiar with Debian). The current Debianisation we're doing will provide Debian and Debian derivates (Ubuntu, Linux Mint, all the apt-stuff) and excessively many others (due to programs like `deb2rpm`, if there weren't already direct rpm support.)

Sorry if this seems aggressive, but I just don't see the point of this.

**Comment by Sesivany** [comment]
OK, I'll change the license. Dunno how I came up with LGPL...

What does the user gain from it? Providing AppData file is the only way for an app or plugin to be installed in GUI in Fedora. If it doesn't provide an appdata file it's not included in the graphical app store.

I don't know how much it is used in other distributions, but the format is distro-agnostic and it's used by GNOME Software (and perhaps by KDE Apper) which is used in other distributions as well.

I can, for sure, keep carrying it downstream, I already have a modified spec file for the Fedora package, but I thought it could be useful for packagers who'd like to package the plugin for other distributions that include software centers that use AppData.

**Comment by BenWiederhake** [comment]
Why AppStream for a non-app?
----------------------------------------

telegram-purple is a plugin to various libpurple-frontends. Thus, it does not fulfill the [requirement for inclusion by AppStream](https://github.com/hughsie/appstream-glib#what-is-an-application):

    Applications are defined in the context of AppStream as such:
    * Installs a desktop file and would be visible in a desktop
    * Has an metadata extractor (e.g. libappstream-builder/plugins/
      asb-plugin-gstreamer.c) and includes an AppData file

telegram-purple does not have a desktop file. It will never be directly visible on the desktop for a user. It does not read metadata. Don't tell me we need an AppData file because we have an AppData file. Fedora manages all metadata in the specfile, which does not need the AppData file (I think).

I was about to suggest that this feature should be removed again, until I realized [the actual definition does include our case](http://www.freedesktop.org/software/appstream/docs/sect-Metadata-Addon.html). However, we should start to insert more `<extends/>`-Tags, so let's collect some frontends in #211 so that the next version of telegram-purple doesn't look like it's pidgin-specific.

**Comment by Sesivany** [comment]
The metainfo file does make the plugin visible to users in UI, see the picture (that's how it looks in Fedora now, sorry for the localization).
telegram-purple-in-software

**Comment by BenWiederhake** [comment]
Could you look up the AppID for each of these apps in Fedora? Most of these don't seem to deliver any AppStream-file by themself. https://github.com/majn/telegram-purple/issues/211

**Pull request merged**
