### PR TITLE
Add support for connecting via IPv6.

### PR DESCRIPTION
**Pull request by elenril**
Enabled through a new "ipv6" option.

### CODE REVIEW

**Comment by BenWiederhake** [comment]
Great work, thanks!

I rebased it against `dev-1.4.0`, the current development branch, and it [builds cleanly](https://travis-ci.org/BenWiederhake/telegram-purple/builds/238069887) and "works for me".

However, before I merge this, I'm curious:
My ISP sucks and I don't have access to the IPv6 internet.  So if I enable this setting, I expected it to fail with some message, but it didn't.  Why?  (This itself is not a blocker, I'm just curious.)
If there's no harm to it anyway, could we maybe even get rid of the checkbox?  (i.e., call `tgl_enable_ipv6` unconditionally.)

**Comment by elenril** [comment]
You mean that it failed silently? Or that it connected with IPv4? Did you clear your auth file before testing? I can't say I understand the connection code perfectly, but AFAIU the list of servers is read from the auth file, so the ipv6 setting actually only matters during the first connection. And looking at the tgl code, it seems to me that tgl_enable_ipv6() would make it use only IPv6, so the setting needs to be there. Unfortunately it's hard for me to test this in a dualstack setting, since my setup is IPv6-only.

**Comment by BenWiederhake** [comment]
It connected with IPv4 (argh, sorry for being unspecific), and I forgot to clear the file.

Hmm.  So it requires magic knowledge on the side of the user.  Ideally, tgp would detect on its own that this setting changed.  The simplest, backwards-compatible way I can come up with is having "two" auth file locations, but only one is actually used: `auth` and `auth.ipv6`.  Then the option can be just extended by "… (restart required)", and all is done.

How much work would that be?  If you think it's too much work, I'll merge this as-is, and extend the option name to say "… (need to manually delete file 'auth'!)" or something.  (Suggestions welcome.)

**Comment by elenril** [comment]
Right, having two auth files sounds like a sensible thing to do. I am somewhat busy right now, so it might take me a week or two to get to it, but I'll look into implementing that.

**Pull request closed without merging**
