### PR TITLE
fix compiler warning about wrong format specifier

### PR DESCRIPTION
**Pull request by stv0g**

### CODE REVIEW

**Comment by EionRobb** [comment]
Windows (well, mingw) doesn't support `%lld`.  Instead the `photo` parameter should be made into a `gint64`

**Comment by EionRobb** [comment]
Unintentional whitespace commit? :)

**Comment by EionRobb** [comment]
Now it's back to not compiling on Windows

**Comment by stv0g** [comment]
Arg, my editor.. Here the last commit is cleaner.

**Pull request closed without merging**
