### PR TITLE
little source code and rpm spec file fix

### PR DESCRIPTION
**Pull request by tuxmaster**
- remove unneeded requirements from rpm spec file
- remove source code fix from rpm spec file
- fix source code permissions

Now without the internal file. :)

### CODE REVIEW

**Comment by BenWiederhake** [comment]
Can someone update the *new* requirement on `gcrypt-devel` and `gcrypt` (see README.md for how those are called in Debian), and remove the (now completely dropped) requirement on OpenSSL.

Also, if you can, find a way to delete the old `/etc/telegram-purple/server.pub`, as now we use a new format (**tgl**pub, see README.md).

**Comment by tuxmaster** [comment]
This must only do for the beta4 branch where your last pull request was  included.

**Comment by BenWiederhake** [comment]
Sure, but it eventually it has to be done before the new version can go into Fedora :P 
I just wanted to notify you that there's still some kind of modification needed.

**Comment by tuxmaster** [comment]
This is no big deal :) I will take a look for it, after this commit is included.

**Comment by BenWiederhake** [comment]
On the beta4 branch, it is! Just like your updated RPM spec :P

**Comment by majn** [comment]
I already merged your PR, thanks

**Pull request closed without merging**
