### PR TITLE
Automated RPM and Debian packages

### PR DESCRIPTION
**Pull request by rtsisyk**
Hi!

This patch adds support for automated RPM/DEB packages using PackPack [[1]] tool. Now you can have ready-to-use packages for every git commit without need to bump versions in `debian/control` and `rpm/purple-telegram.spec` files. Proposed `.travis.yml` automatically bumps versions, creates a source tarball and builds packages on every commit [[2]]. It is also possible to deploy these packages to [packagecloud.io](https://packagecloud.io) or Amazon S3 using Travis CI. See more examples in [[3]].

This commit is based against debian-master branch, because it requires `debian/` directory for Debian packages.

[1]: https://github.com/packpack/packpack#packpack
[2]: https://travis-ci.org/rtsisyk/telegram-purple/builds/204933482
[3]: https://github.com/tarantool/tarantool-c/blob/master/.travis.yml#L87

### CODE REVIEW

**Comment by BenWiederhake** [comment]
Nice idea!  Awesome work, thank you!

Unsorted braindump and sanity check:
- The `debian/` folder contains some important files (like `copyright` and `source/options`) that I think really need to make it into the `.deb` file.
- That folder is currently only available on branches `debian-master` and `debian-develop`
- PackPack seems to require a lot of `.travis.yml` config, which is understandable, but might clash with our tests
- Our tests should be automatically executed by `dh_auto_test`, at least they always did when I built the package on my machine
- On Travis, it seems that `dh_auto_test -O--parallel` [is being called](https://travis-ci.org/rtsisyk/telegram-purple/jobs/204933488#L1596) but doesn't do anything.
- The version strings are slightly misleading, as they indicate the amount of commits (41) to be the Debian packaging iteration.  [Example.](https://travis-ci.org/rtsisyk/telegram-purple/jobs/204933488#L1645)  Specifically, `1.2.4-41` would mean that this is the 41st iteration of making and publishing a Debian package out of the software.

So I have two comments:

As with everything: Yes, it's shiny, it's new, it's awesome, but is it really needed?  After all, it only builds x64 packages, introduces new complexity, needs to be maintained, and packages are only really relevant for actual releases.  Finally, although the "Goldan Path" feels pretty stable, a lot of things (secret chats, file transfers, supergroups, exotic messages, UI issues around audio) are not really perfect.  I believe that putting a pre-built `.deb` or `.rpm` online is a great way to say "look at this, it's perfect, ready to use, there's nothing you'll need to do on your own" which just isn't the case yet.  Someone who can't `make && sudo make install` on their own probably won't be able to do any troubleshooting when things go wrong.  And things *do* go wrong, see issue tracker.  
  Then again, I might be overly pessimistic.  @majn, what do you say?

Either way: Is there a nice way to indicate that a PackPack-built package is not to be considered "the real thing"?  I suggest a format like `1.2.4-1+packpack41` or similar, where `1.2.4-1` is the version according to `dpkg-parsechangelog -S Version` (usage might vary), and `41` is the same number (git commits since last version, I guess).

**Comment by rtsisyk** [comment]
> The debian/ folder contains some important files (like copyright and source/options) that I think really need to make it into the .deb file.
> That folder is currently only available on branches debian-master and debian-develop

Please note I changed nothing in debian/ folder itself. This pull request is against debian-master branch.  I have no idea why debian-master branch isn't merged into master.

> PackPack seems to require a lot of .travis.yml config, which is understandable, but might clash with our tests

Yeah, Travis CI is tricky in this sense.

> Our tests should be automatically executed by dh_auto_test, at least they always did when I built the package on my machine
> On Travis, it seems that dh_auto_test -O--parallel is being called but doesn't do anything.

I agree. I usually add "make test" to my repositories or override dh_auto_test.

> The version strings are slightly misleading, as they indicate the amount of commits (41) to be the Debian packaging iteration. Example. Specifically, 1.2.4-41 would mean that this is the 41st iteration of making and publishing a Debian package out of the software.

Exactly. According to Debian policies and Fedora Guidelines, VERSION should be the actual version of software, whereas RELEASE is the number of times this package has been repackaged by a package maintaner or rebuilt by automated tools. I usually add "major.minor" annotated tags in repos, so "1.3-10-g766335c" can be easily converted to VERSION=1.3.10 RELEASE=1. It is how Packpack works by default.  

In this pull request I especially overrode VERSION and RELEASE to match the **current scheme** used by this project.

> As with everything: Yes, it's shiny, it's new, it's awesome, but is it really needed?

PackPack has been used to package dozens of git repositories in https://github.com/tarantool organization for the last couple years. It is not shiny, but it removes some pain from CI scripts.

> After all, it only builds x64 packages, introduces new complexity, needs to be maintained, and packages are only really relevant for actual releases. 

It uses Docker under the hood. Docker supports i386, x86_64, armv7 and even aarch64. Of course, you will need a native host for the last two. PackPack allow you to build packages for all popular Linux distributions on each git commit, so I suppose that these packages are always actual.

> Either way: Is there a nice way to indicate that a PackPack-built package is not to be considered "the real thing"? I suggest a format like 1.2.4-1+packpack41 or similar, where 1.2.4-1 is the version according to dpkg-parsechangelog -S Version (usage might vary), and 41 is the same number (git commits since last version, I guess).

Yeas, it is possible. Just override VERSION and RELEASE environment variables.

Anyway, I just proposed a way how to get packages for your users on each git commit. I think that my GitHub + Travis CI + PackPack + PackageCloud solution is significantly easier and more flexible than, say, [Open Build Service](https://github.com/dequis/purple-facebook/blob/master/.travis/obs.sh). It is also possible to use PackPack without Travis CI. For instance, we installed Jenkins couple weeks ago, added couple lines (git clone --recursive xxx; OS=XX DIST=YY packpack) to it, and obtained the same packages as from Travis CI.

**Comment by rtsisyk** [comment]
Any news?

**Comment by BenWiederhake** [comment]
Sorry for not responding for so long, but I'm just not convinced.

- introduces new complexity (interaction with Travis, or whatever platform)
- needs to be maintained
- only really relevant for actual releases, which are rare enough to do it by hand ([it will eat more than 5 minutes](https://xkcd.com/1205/))
- tgp is not stable. Putting a pre-built .deb or .rpm online sets wrong expectations. Someone who can't `./configure && make && sudo make install` by themselves probably won't enjoy it anyway, nor send good bug reports.

Note that this doesn't really apply to the Windows installer, as: it doesn't run on Travis; it replaces a long, collaborative, and brittle chore when releasing; building it by yourself is so difficult on Windows that I preferred cross-building.

Packpack looks awesome, it just doesn't apply here in my eyes.  
I'll cherry-pick the first commit, though.  Thanks!

If something about this changes, feel free to re-open.

**Pull request closed without merging**
