### PR TITLE
Fix appdata build for rpm.

### PR DESCRIPTION
**Pull request by tuxmaster**

### CODE REVIEW

**Comment by BenWiederhake** [comment]
Are you sure that this is a good idea?

    %{_datadir}/appdata/telegram-purple.metainfo.xml

Please note this commit already on master: https://github.com/majn/telegram-purple/commit/1cf511f52645cde424109031030255a60bb9c0ad


	mkdir -m $(DIR_PERM) -p $(DESTDIR)$(datarootdir)/appdata
	install -m $(FILE_PERM) telegram-purple.metainfo.xml $(DESTDIR)$(datarootdir)/appdata/telegram-purple.metainfo.xml

**Comment by tuxmaster** [comment]
This file is installed by make install of the master build.
I don't know why 1.2.4 include this.
%{_datadir} is the rpm macro for /usr/share

**Comment by BenWiederhake** [comment]
I wanted to inform you that your pull request means that the appdata file would be installed *twice*, since the Makefile now installs the appdata file. (AppStream is a cross-distro project, so doing that from the Makefile should be a good idea.)

Do you intentionally want to install the file twice, or did we surprise you be the change? (Where the "change" is "Makefile suddenly installs this file".)

**Comment by tuxmaster** [comment]
The file is only installed once by the make file.
%{_datadir}/appdata/telegram-purple.metainfo.xml are needed to package the file.
Or why do you think it will be packaged twice?

**Comment by BenWiederhake** [comment]
Oh! Sorry, it seems I completely misunderstood how the specfile works. I thought it would try to copy the appdata file, independently of what the Makefile already does.

Sorry, my fault, and now I believe this is ready to be pulled. (@majn should do that, not me.)

**Comment by majn** [comment]
@tuxmaster what distribution are you packaging telegram-purple for?

**Comment by tuxmaster** [comment]
Fedora+CentOS

**Pull request merged**
