### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by redsn0w0**
Fixed the telegram group invite link.

### CODE REVIEW

**Comment by BenWiederhake** [comment]
I don't quite see the difference.  Is it only the linebreak?

**Comment by redsn0w0** [comment]
Try to join the group https://github.com/majn/telegram-purple you will see that it you will redirect you there: https://github.com/majn/telegram-purple/blob/master/goo.gl/VudXys

**Comment by criztovyl** [comment]
It's the https-Part not the line break :)
@majn removed it as he refreshed the link as of #334 (c52854a)

**Comment by BenWiederhake** [comment]
Ah, now I get it!  Yeah, thank you, you're right.

However, we intended to remove clickable links due to spam, which is why the "other" link (towards the end, in "FAQ > Group chat") isn't clickable.

Since the links disagree: @majn, pick which link you want to preserve.

**Pull request merged**
