### PR TITLE
Add support for sending HTML messages

### PR DESCRIPTION
**Pull request by EionRobb**
This adds HTML message support to send messages by flagging the connection as HTML-capable and setting the HTML flag in outgoing messages.

(Sorry for the messy branch.  If you can tell me how to remove commits from a PR I'd be grateful.)

### CODE REVIEW

**Comment by majn** [comment]
Doesn't seem to work cause libpurple creates uppercase HTML tags and libtgl only recognizes lowercases tags.

**Comment by majn** [comment]
Just noticed that generated message entities aren't actually used by libtgl, they are just parsed and never inserted into the message.

**Comment by EionRobb** [comment]
Some weird github issue auto-closed this PR, but since it doesn't work without change (either to telegram-purple to convert to lowercase tags, or to libtgl to support case-insensitive tags) it's not worth keeping open at the moment anyway

**Comment by BenWiederhake** [comment]
Please note that the four lines shown by https://github.com/majn/telegram-purple/pull/257/files are already changed, so there's nothing to do anyway.

**Pull request closed without merging**
