### PR TITLE
Fix failure when trying to move downloaded file across partitions.

### PR DESCRIPTION
**Pull request by Maato**
This fixes issue: #230

### CODE REVIEW

**Comment by BenWiederhake** [comment]
Looks good to me, just needs to be tested before being merged.

**Comment by bobvanderlinden** [comment]
I tested this. Previously downloaded files were stuck in `~/.purple/telegram-purple/+phonenumber/downloads` and would not show up at the destination directory. Clicking the hyperlink for the file would not do anything.

With this patch the file successfully moved to its destination directory.

**Comment by majn** [comment]
It adds a dependency to libgio, which breaks the pidgin build on OSX and the Adium package.

**Comment by majn** [comment]
I have to research why exactly libgio is only present in some builds, eventually it needs to be declares as a dependency.

**Comment by bobvanderlinden** [comment]
What would a good solution for this PR be? Should it keep using gio (and wait for the OSX and Adium builds to add it) or should it use a self-fabricated method of moving the file?

**Comment by BenWiederhake** [comment]
Strange, libgio is already a dependency of pidgin under Debian, that's why I acked him using gio (I don't know where and how, but I do remember something like this happening). In fact, in Debian libglib and libgio are the same:
```
$ dpkg-query -L libglib2.0-0 | grep gio
/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.4800.0
/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
```

If we really end up having to use something "self-fabricated", then please make it more efficient than the other PR (i.e. don't go char by char). At the very least, copy it 4K-by-4K or something.

**Comment by BenWiederhake** [comment]
Any news on finding out why libgio2 is only present in some builds?

**Comment by BenWiederhake** [comment]
Closing due to inactivity.

**Pull request closed without merging**
