### PR TITLE
Fix README.md prerequires for deb

### PR DESCRIPTION
**Pull request by rshadow**

### CODE REVIEW

**Comment by BenWiederhake** [comment]
`gettext` and `debhelper` are definitely correct. Thanks!

Did `dh-autoreconf` automatically install for you? If not (and I don't think so), can you squash it into the PR?

@majn: Merging into master seems like a bad thing, but for this PR is a good thing to do. If we pull it to `debian-*`, then the public `README` doesn't get updated (bad). Likewise are the `dev-*` branches unsuitable, as it's unnecessary. Hence, basing on master is actually a good idea this time.

**Comment by rshadow** [comment]
I do not know what is `dh-autoreconf`. And I can not find it in Debian.

**Comment by rshadow** [comment]
I build the deb package without installed `dh-autoreconf`. So it is not needed?

**Comment by BenWiederhake** [comment]
Argh, sorry. `dh-autoreconf` is used in the branch `debian-develop`, which I haven't published yet, so my request was invalid.

So `dh-autoreconf` is currently not needed, true, and this pull is accepted.

However, you will "soon" need it, so `apt-get install dh-autoreconf` at some point in the future :P

**Pull request merged**
