### PR TITLE
Fix build system

### PR DESCRIPTION
**Pull request by BenWiederhake**
There already is a file that knows how to build libtgl, and it is `tgl/Makefile`. There already is a file that knows how to build tl-parser, and it is `tgl/tl-parser/Makefile`. There is no need for a `Makefile.tlg` or anything, and this approach is highly fragile (it breaks as soon any change in general configuration or `tgl/Makefile.in` occurs).

These two patches will do, in order:

- Let the projects build themselves. (Kicks out `Makefile.tgl` and `Makefile.tl-parse`)
- Empower telegram-purple to build libtgl from pristine source (e.g. when not even `tgl/configure` or `tgl/config.h.in` exist). I need this mostly for myself and can totally understand if you don't want this second patch.

### CODE REVIEW

**Comment by BenWiederhake** [comment]
Err, wait before you pull. I missed something.

**Comment by majn** [comment]
Don't worry, I don't merge any pull request until I've tested it. Unfortunately I don't have time to test this until at least tomorrow evening.

**Comment by BenWiederhake** [comment]
Fortunately*

This means I don't waste yur time until then :P

**Comment by BenWiederhake** [comment]
I don't get it.

It just doesn't work. No error message whatsoever. It simply doesn't recognize the plugin when I change *anything*.

The only difference I can find is that in the file`tgl/Makefile`, the object `${TGL_OBJECTS_AUTO}` is not added into the library `libtgl.a`. However, `nm` doesn't find any undefined symbols, which is the only kind of error of which I can think.

What other kinds of error could produce the behaviour "plugin silently doesn't get loaded into pidgin, even when running with -d"?

**Comment by majn** [comment]
If the plugin is present in the libpurple plugin dir /usr/lib/purple-2/plugins/telegram-purple.so or something like that there should definitely be some form of message in the pidgin log that tells you about the attempt to load it.

It should look something like that:

(14:52:28) plugins: probing /usr/lib64/purple-2/libbonjour.so
(14:52:28) plugins: probing /usr/lib64/purple-2/libsimple.so
(14:52:28) plugins: probing /usr/lib64/purple-2/statenotify.so
(14:52:28) plugins: probing /usr/lib64/purple-2/newline.so
(14:52:28) plugins: probing /usr/lib64/purple-2/eight_ball.so
(14:52:28) plugins: probing /usr/lib64/purple-2/napster.so
(14:52:28) plugins: probing /usr/lib64/purple-2/nss-prefs.so
(14:52:28) plugins: probing /usr/lib64/purple-2/libyahoojp.so
(14:52:28) plugins: probing /usr/lib64/purple-2/telegram-purple.so
...

**Comment by BenWiederhake** [comment]
(15:03:51) plugins: /usr/lib/purple-2/telegram-purple.so is not loadable: undefined symbol: tl_type_update

Hooray! An error message. Now that's something with which I can work.

It's strange that these messages don't appear in the Pidgin debug window.

**Comment by BenWiederhake** [comment]
(Most importantly that I can write a small sample program that links successfully against libtgl.a. It seems I don't know enough yet about that topic.)

**Comment by majn** [comment]
Are you sure that you compiled and linked all autogenerated files in your Makefile?

**Comment by BenWiederhake** [comment]
Yup, this is related to what I mentioned earlier: `tgl/Makefile` leaves out the autogenerated objects, a.k.a. ${TGL_OBJECTS_AUTO}.

**Comment by BenWiederhake** [comment]
Note that https://github.com/majn/tgl/pull/1 now needs to be merged *before* this is even tested. (Also reported upstream as https://github.com/vysheng/tgl/pull/43 ).

If you really *really* need to, here's how: https://gist.github.com/BenWiederhake/acefb60d4aaaefaa0862 (Sorry for the complications, but I really don't want to enter my repo into .gitmodules.)

Tested and verified with a fresh local checkout.

Also, this finally allows me to change the build system of libtgl, which wasn't possible previously.

**Comment by BenWiederhake** [comment]
Sorry for the lots of rebasing, but now it's stable, I think.

**Comment by BenWiederhake** [comment]
Nope, still not quite it. Dammit.

**Comment by BenWiederhake** [comment]
head->desk

Works exactly as intended, I just forgot to refresh.

**Pull request closed without merging**
