### PR TITLE
Fix ellipses in translatable strings

### PR DESCRIPTION
**Pull request by piotrdrag**

### CODE REVIEW

**Comment by BenWiederhake** [comment]
"master" doesn't currently host the translation efforts, but thanks for the patch! We'll definitely include it.

**Comment by majn** [comment]
Thanks for making this PR, but looking around the Pidgin source seems like three regular dots is the way of doing things in libpurple. There is not a single instance of "…" in the whole source tree, and I want to stay consistent with the other plugins.

Is there any specific reason why the special char should be used instead of dots?

**Comment by BenWiederhake** [comment]
I have already prepared inclusion of this change, see the above references. (Sorry for the duplicates, but I prefer rebasing over merging.)

The special char should be preferred because it is "the right thing". Text-to-speech programs will read it more meaningfully, and it takes up less space. Also, it kinda serves as a sanity check of the toolchain (git, editors, translation tools, transifex, g++, etc.) because it's the only non-ASCII thing in the code base so far.

These aren't overwhelming reasons, yeah, sorry, but I believe they are worth the "inconsistency", which is visually rather small. Btw: Pidgin uses the style "phrase..." without any spaces after the word, which is wrong anyway in German (and probably English, too).

**Comment by BenWiederhake** [comment]
@majn decided against it, in order to stay consistent with the rest of libpurple (or rather: pidgin)

**Pull request closed without merging**
