### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RobFog**
* Fix a typo.
* Mention Adium in secret chat instructions.

### CODE REVIEW

**Comment by RobFog** [comment]
The CI build failed?

**Comment by BenWiederhake** [comment]
Yup, because Travis dun goofed up.  I have no idea how to restart it.

Come to think of it, I have no idea why I haven't merged this yet.  Thanks! :)

**Comment by BenWiederhake** [comment]
Merged into the dev branch.  It will automatically land in `master` when (if?) the next release comes up.

**Comment by RobFog** [comment]
> Yup, because Travis dun goofed up. I have no idea how to restart it.
Ah. This seems to be a regular occurrence. At least I've seen it happen at the MuseScore project as well.

> Come to think of it, I have no idea why I haven't merged this yet. Thanks! :)
Thank you!

**Pull request closed without merging**
